version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ipa-ucdavis-edu.env
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./dist:/usr/share/nginx/html
    ports:
      - 80
