import './rolesTable.css';

let rolesTable = function ($rootScope, WorkgroupActionCreators, WorkgroupService) {
	return {
		restrict: 'E',
		template: require('./rolesTable.html'),
		replace: true,
		scope: {
			userRoles: '<',
			activeRoleId: '<',
			users: '<',
			ui: '<'
		},
		link: function(scope) {

			
			scope.view = {
				loadingPeople: false,
				noResults: false
			};

			scope.removeUserRole = function (userRole) {
				WorkgroupActionCreators.removeRoleFromUser(userRole.userId, userRole.roleId, userRole);
			};

			scope.clearUserSearch = function () {
				scope.users.newUser = {};
				scope.users.searchQuery = "";
				scope.view.noResults = false;
			};

			scope.searchOnChange = function () {
				scope.view.noResults = false;
				scope.users.newUser = {};
				console.log(scope.users.list) // eslint-disable-line
			};

			scope.searchUsers = function (query) {
				return WorkgroupService.searchUsers(scope.ui.workgroupId, query).then(function (userSearchResults) {
					return userSearchResults;
				}, function () {
					$rootScope.$emit('toast', {message: "Could not search users.", type: "ERROR"});
				});
			};

			scope.searchUsersResultSelected = function ($item) {
				scope.users.newUser = $item;
			};

			scope.addUserToWorkgroup = function() {
				scope.users.newUser;
				WorkgroupActionCreators.createUser(scope.ui.workgroupId, scope.users.newUser, scope.activeRoleId);
				scope.clearUserSearch();
			};

			scope.result = [{  
				"id":3,
				"email":"ltwheeler@ucdavis.edu",
				"firstName":"Lloyd",
				"lastName":"Wheeler",
				"displayName":"Lloyd Wheeler",
				"lastAccessed":1544777988000,
				"userRoles":[  
					{  
						"id":5029,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":3,
						"role":"academicPlanner"
					},
					{  
						"id":6789,
						"workgroupId":20,
						"roleId":15,
						"instructorTypeId":3,
						"userId":3,
						"role":"instructor"
					},
					{  
						"id":8301,
						"workgroupId":0,
						"roleId":3,
						"instructorTypeId":null,
						"userId":3,
						"role":"admin"
					}
				],
				"placeholder":false,
				"iamId":1000025788,
				"name":"Wheeler, Lloyd",
				"loginId":"guilden"
			},
			{  
				"id":1,
				"email":"cmthielen@ucdavis.edu",
				"firstName":"Christopher",
				"lastName":"Thielen",
				"displayName":"Christopher Thielen",
				"lastAccessed":1548268972000,
				"userRoles":[  
					{  
						"id":5066,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":5112,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":1,
						"role":"academicPlanner"
					},
					{  
						"id":5140,
						"workgroupId":46,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":5145,
						"workgroupId":77,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":5146,
						"workgroupId":77,
						"roleId":2,
						"instructorTypeId":null,
						"userId":1,
						"role":"academicPlanner"
					},
					{  
						"id":5338,
						"workgroupId":0,
						"roleId":3,
						"instructorTypeId":null,
						"userId":1,
						"role":"admin"
					},
					{  
						"id":5433,
						"workgroupId":74,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":5435,
						"workgroupId":74,
						"roleId":12,
						"instructorTypeId":null,
						"userId":1,
						"role":"studentMasters"
					},
					{  
						"id":5456,
						"workgroupId":13,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":6908,
						"workgroupId":20,
						"roleId":15,
						"instructorTypeId":4,
						"userId":1,
						"role":"instructor"
					},
					{  
						"id":6909,
						"workgroupId":74,
						"roleId":15,
						"instructorTypeId":4,
						"userId":1,
						"role":"instructor"
					},
					{  
						"id":6911,
						"workgroupId":46,
						"roleId":15,
						"instructorTypeId":4,
						"userId":1,
						"role":"instructor"
					},
					{  
						"id":8297,
						"workgroupId":11,
						"roleId":13,
						"instructorTypeId":null,
						"userId":1,
						"role":"studentPhd"
					},
					{  
						"id":8298,
						"workgroupId":11,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":9385,
						"workgroupId":87,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":9475,
						"workgroupId":87,
						"roleId":15,
						"instructorTypeId":7,
						"userId":1,
						"role":"instructor"
					},
					{  
						"id":9491,
						"workgroupId":69,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":10173,
						"workgroupId":24,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":10174,
						"workgroupId":24,
						"roleId":15,
						"instructorTypeId":6,
						"userId":1,
						"role":"instructor"
					},
					{  
						"id":10175,
						"workgroupId":24,
						"roleId":11,
						"instructorTypeId":null,
						"userId":1,
						"role":"instructionalSupport"
					},
					{  
						"id":11038,
						"workgroupId":66,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":11044,
						"workgroupId":66,
						"roleId":15,
						"instructorTypeId":6,
						"userId":1,
						"role":"instructor"
					},
					{  
						"id":11229,
						"workgroupId":15,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":11230,
						"workgroupId":15,
						"roleId":15,
						"instructorTypeId":7,
						"userId":1,
						"role":"instructor"
					},
					{  
						"id":11473,
						"workgroupId":75,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1,
						"role":"presence"
					},
					{  
						"id":11476,
						"workgroupId":75,
						"roleId":15,
						"instructorTypeId":4,
						"userId":1,
						"role":"instructor"
					},
					{  
						"id":11477,
						"workgroupId":75,
						"roleId":13,
						"instructorTypeId":null,
						"userId":1,
						"role":"studentPhd"
					}
				],
				"placeholder":false,
				"iamId":1000031958,
				"name":"Thielen, Christopher",
				"loginId":"cthielen"
			},
			{  
				"id":2399,
				"email":"cwjwong@ucdavis.edu",
				"firstName":"Jarold",
				"lastName":"Wong",
				"displayName":"Jarold Wong",
				"lastAccessed":1548268942000,
				"userRoles":[  
					{  
						"id":8299,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":2399,
						"role":"academicPlanner"
					},
					{  
						"id":8300,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":2399,
						"role":"presence"
					},
					{  
						"id":8311,
						"workgroupId":20,
						"roleId":15,
						"instructorTypeId":7,
						"userId":2399,
						"role":"instructor"
					},
					{  
						"id":11525,
						"workgroupId":20,
						"roleId":13,
						"instructorTypeId":null,
						"userId":2399,
						"role":"studentPhd"
					}
				],
				"placeholder":false,
				"iamId":null,
				"name":"Wong, Jarold",
				"loginId":"jiwung"
			},
			{  
				"id":569,
				"email":"jeremy@ucdavis.edu",
				"firstName":"Jeremy",
				"lastName":"Phillips",
				"displayName":"Jeremy M Phillips",
				"lastAccessed":1541419847000,
				"userRoles":[  
					{  
						"id":5149,
						"workgroupId":77,
						"roleId":9,
						"instructorTypeId":null,
						"userId":569,
						"role":"presence"
					},
					{  
						"id":5150,
						"workgroupId":77,
						"roleId":12,
						"instructorTypeId":null,
						"userId":569,
						"role":"studentMasters"
					},
					{  
						"id":9497,
						"workgroupId":20,
						"roleId":15,
						"instructorTypeId":4,
						"userId":569,
						"role":"instructor"
					},
					{  
						"id":10398,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":569,
						"role":"academicPlanner"
					},
					{  
						"id":11526,
						"workgroupId":20,
						"roleId":13,
						"instructorTypeId":null,
						"userId":569,
						"role":"studentPhd"
					}
				],
				"placeholder":false,
				"iamId":1000016994,
				"name":"Phillips, Jeremy",
				"loginId":"jeremy"
			},
			{  
				"id":741,
				"email":"cbeck@ucdavis.edu",
				"firstName":"Carol",
				"lastName":"McMasters-Stone",
				"displayName":"Carol McMasters-Stone",
				"lastAccessed":null,
				"userRoles":[  
					{  
						"id":11207,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":741,
						"role":"presence"
					},
					{  
						"id":11208,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":741,
						"role":"academicPlanner"
					}
				],
				"placeholder":false,
				"iamId":1000004626,
				"name":"McMasters-Stone, Carol",
				"loginId":"carolm"
			},
			{  
				"id":743,
				"email":"cjbrick@ucdavis.edu",
				"firstName":"Christopher",
				"lastName":"Brick",
				"displayName":"Christopher Brick",
				"lastAccessed":null,
				"userRoles":[  
					{  
						"id":11209,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":743,
						"role":"presence"
					},
					{  
						"id":11210,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":743,
						"role":"academicPlanner"
					}
				],
				"placeholder":false,
				"iamId":1000023177,
				"name":"Brick, Christopher",
				"loginId":"cjbrick"
			},
			{  
				"id":742,
				"email":"jwtrask@ucdavis.edu",
				"firstName":"Jeff",
				"lastName":"Trask",
				"displayName":"Jeff Trask",
				"lastAccessed":null,
				"userRoles":[  
					{  
						"id":11211,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":742,
						"role":"presence"
					},
					{  
						"id":11212,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":742,
						"role":"academicPlanner"
					}
				],
				"placeholder":false,
				"iamId":1000024728,
				"name":"Trask, Jeff",
				"loginId":"jwtrask"
			},
			{  
				"id":1299,
				"email":"jmcarlson@ucdavis.edu",
				"firstName":"Janine",
				"lastName":"Carlson",
				"displayName":"Janine Carlson",
				"lastAccessed":1511861631000,
				"userRoles":[  
					{  
						"id":11214,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":1299,
						"role":"academicPlanner"
					},
					{  
						"id":11215,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":1299,
						"role":"presence"
					}
				],
				"placeholder":false,
				"iamId":1000030369,
				"name":"Carlson, Janine",
				"loginId":"jmcarlso"
			},
			{  
				"id":3709,
				"email":"bvbaker@ucdavis.edu",
				"firstName":"Brandon",
				"lastName":"Baker",
				"displayName":"Brandon Vernon Baker",
				"lastAccessed":null,
				"userRoles":[  
					{  
						"id":11216,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":3709,
						"role":"presence"
					},
					{  
						"id":11217,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":3709,
						"role":"academicPlanner"
					}
				],
				"placeholder":false,
				"iamId":null,
				"name":"Baker, Brandon",
				"loginId":"bvbaker"
			},
			{  
				"id":3710,
				"email":"hsotelo@ucdavis.edu",
				"firstName":"Hector",
				"lastName":"Sotelo",
				"displayName":"Hector Sotelo",
				"lastAccessed":null,
				"userRoles":[  
					{  
						"id":11218,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":3710,
						"role":"presence"
					},
					{  
						"id":11219,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":3710,
						"role":"academicPlanner"
					}
				],
				"placeholder":false,
				"iamId":null,
				"name":"Sotelo, Hector",
				"loginId":"hsotelo"
			},
			{  
				"id":744,
				"email":"sadyer@ucdavis.edu",
				"firstName":"Scott",
				"lastName":"Dyer",
				"displayName":"Scott A Dyer",
				"lastAccessed":null,
				"userRoles":[  
					{  
						"id":11220,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":744,
						"role":"academicPlanner"
					},
					{  
						"id":11221,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":744,
						"role":"presence"
					}
				],
				"placeholder":false,
				"iamId":1000021195,
				"name":"Dyer, Scott",
				"loginId":"sadyer"
			},
			{  
				"id":3711,
				"email":"sjmosher@ucdavis.edu",
				"firstName":"Samuel",
				"lastName":"Mosher",
				"displayName":"Samuel J Mosher",
				"lastAccessed":null,
				"userRoles":[  
					{  
						"id":11222,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":3711,
						"role":"presence"
					},
					{  
						"id":11223,
						"workgroupId":20,
						"roleId":2,
						"instructorTypeId":null,
						"userId":3711,
						"role":"academicPlanner"
					}
				],
				"placeholder":false,
				"iamId":null,
				"name":"Mosher, Samuel",
				"loginId":"sjmosher"
			},
			{  
				"id":3712,
				"email":"sarshad@ucdavis.edu",
				"firstName":"Sadaf",
				"lastName":"Arshad",
				"displayName":"Sadaf Arshad",
				"lastAccessed":1544714437000,
				"userRoles":[  
					{  
						"id":11226,
						"workgroupId":20,
						"roleId":13,
						"instructorTypeId":null,
						"userId":3712,
						"role":"studentPhd"
					},
					{  
						"id":11227,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":3712,
						"role":"presence"
					}
				],
				"placeholder":false,
				"iamId":null,
				"name":"Arshad, Sadaf",
				"loginId":"sdf9235"
			},
			{  
				"id":3813,
				"email":"mromeroval@ucdavis.edu",
				"firstName":"Mauricio",
				"lastName":"Romero Valenzuela",
				"displayName":"Mauricio Romero Valenzuela",
				"lastAccessed":1549308721000,
				"userRoles":[  
					{  
						"id":11527,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":3813,
						"role":"presence"
					},
					{  
						"id":11528,
						"workgroupId":20,
						"roleId":15,
						"instructorTypeId":7,
						"userId":3813,
						"role":"instructor"
					},
					{  
						"id":11534,
						"workgroupId":0,
						"roleId":3,
						"instructorTypeId":null,
						"userId":3813,
						"role":"admin"
					}
				],
				"placeholder":false,
				"iamId":null,
				"name":"Romero Valenzuela, Mauricio",
				"loginId":"romerov"
			},
			{  
				"id":3815,
				"email":"sadshah@ucdavis.edu",
				"firstName":"Sadaf",
				"lastName":"Shah",
				"displayName":"Sadaf Ali Shah",
				"lastAccessed":null,
				"userRoles":[  
					{  
						"id":11536,
						"workgroupId":20,
						"roleId":9,
						"instructorTypeId":null,
						"userId":3815,
						"role":"presence"
					}
				],
				"placeholder":false,
				"iamId":null,
				"name":"Shah, Sadaf",
				"loginId":"ssha1520"
			},
			{
				"rowType":"subheader",
				"displayName":"Courses"
			},{  
				"id":83429,
				"displayName":"Prob & Sta Model for CS",
				"subjectCode":"ECS",
				"courseNumber":"132",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83430,
				"displayName":"Ethics in an Age of Tech",
				"subjectCode":"ECS",
				"courseNumber":"188",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83432,
				"displayName":"Programming Languages",
				"subjectCode":"ECS",
				"courseNumber":"140A",
				"effectiveTermCode":"201701",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83433,
				"displayName":"Computer Architecture",
				"subjectCode":"ECS",
				"courseNumber":"154A",
				"effectiveTermCode":"201701",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83450,
				"displayName":"Prog Lang&Compilers",
				"subjectCode":"ECS",
				"courseNumber":"289C",
				"effectiveTermCode":"198510",
				"sequencePattern":"001",
				"unitsLow":1.0,
				"unitsHigh":5.0,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83451,
				"displayName":"Computer Sci Theory",
				"subjectCode":"ECS",
				"courseNumber":"189A",
				"effectiveTermCode":"200103",
				"sequencePattern":"001",
				"unitsLow":1.0,
				"unitsHigh":5.0,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83452,
				"displayName":"Computer Architecture",
				"subjectCode":"ECS",
				"courseNumber":"201A",
				"effectiveTermCode":"200210",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83456,
				"displayName":"Parallel Architectures",
				"subjectCode":"ECS",
				"courseNumber":"158",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83457,
				"displayName":"Software Engineering",
				"subjectCode":"ECS",
				"courseNumber":"160",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83462,
				"displayName":"Programming Tools",
				"subjectCode":"ECS",
				"courseNumber":"161",
				"effectiveTermCode":"201710",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83464,
				"displayName":"Ethics in an Age of Tech",
				"subjectCode":"ECS",
				"courseNumber":"188",
				"effectiveTermCode":"201610",
				"sequencePattern":"002",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83466,
				"displayName":"Ethics in an Age of Tech",
				"subjectCode":"ECS",
				"courseNumber":"188",
				"effectiveTermCode":"201610",
				"sequencePattern":"003",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83471,
				"displayName":"Intro to Programming",
				"subjectCode":"ECS",
				"courseNumber":"010",
				"effectiveTermCode":"201610",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":"This is too many instructors.",
				"scheduleId":221
			},
			{  
				"id":83472,
				"displayName":"Theory Computation",
				"subjectCode":"ECS",
				"courseNumber":"120",
				"effectiveTermCode":"201610",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83473,
				"displayName":"Algorithm Design",
				"subjectCode":"ECS",
				"courseNumber":"122A",
				"effectiveTermCode":"201610",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{
				"rowType":"divider"
			},
			{  
				"id":83474,
				"displayName":"Computer Networks",
				"subjectCode":"ECS",
				"courseNumber":"152A",
				"effectiveTermCode":"201610",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				98
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83476,
				"displayName":"Discrete Math for CS",
				"subjectCode":"ECS",
				"courseNumber":"020",
				"effectiveTermCode":"201701",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83477,
				"displayName":"Software &Obj-Orient Prg",
				"subjectCode":"ECS",
				"courseNumber":"040",
				"effectiveTermCode":"201701",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83478,
				"displayName":"Machine Dependent Prog",
				"subjectCode":"ECS",
				"courseNumber":"050",
				"effectiveTermCode":"201701",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				98
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83479,
				"displayName":"Programming Languages",
				"subjectCode":"ECS",
				"courseNumber":"140A",
				"effectiveTermCode":"201701",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83480,
				"displayName":"Computer Architecture",
				"subjectCode":"ECS",
				"courseNumber":"154A",
				"effectiveTermCode":"201701",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83481,
				"displayName":"Programming&Prob Solving",
				"subjectCode":"ECS",
				"courseNumber":"030",
				"effectiveTermCode":"201703",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83482,
				"displayName":"Data Structures and Prog",
				"subjectCode":"ECS",
				"courseNumber":"060",
				"effectiveTermCode":"201703",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83483,
				"displayName":"Bioinformatics",
				"subjectCode":"ECS",
				"courseNumber":"124",
				"effectiveTermCode":"201703",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				98
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83484,
				"displayName":"Intro to Programming",
				"subjectCode":"ECS",
				"courseNumber":"010",
				"effectiveTermCode":"201610",
				"sequencePattern":"B",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83485,
				"displayName":"Algorithm Design",
				"subjectCode":"ECS",
				"courseNumber":"122A",
				"effectiveTermCode":"201610",
				"sequencePattern":"B",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83486,
				"displayName":"Computer Sci Theory",
				"subjectCode":"ECS",
				"courseNumber":"289A",
				"effectiveTermCode":"198510",
				"sequencePattern":"001",
				"unitsLow":1.0,
				"unitsHigh":5.0,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83489,
				"displayName":"Security",
				"subjectCode":"ECS",
				"courseNumber":"289M",
				"effectiveTermCode":"200101",
				"sequencePattern":"001",
				"unitsLow":1.0,
				"unitsHigh":5.0,
				"year":2018,
				"tagIds":[  
				98
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83490,
				"displayName":"Theory Of Computation",
				"subjectCode":"ECS",
				"courseNumber":"220",
				"effectiveTermCode":"200210",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83492,
				"displayName":"Comp Structural Bioinfo",
				"subjectCode":"ECS",
				"courseNumber":"129",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				98
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83493,
				"displayName":"Scripting Languages",
				"subjectCode":"ECS",
				"courseNumber":"145",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83494,
				"displayName":"Computer Architecture",
				"subjectCode":"ECS",
				"courseNumber":"154B",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83495,
				"displayName":"Information Interfaces",
				"subjectCode":"ECS",
				"courseNumber":"163",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83503,
				"displayName":"Algorithm Design",
				"subjectCode":"ECS",
				"courseNumber":"122B",
				"effectiveTermCode":"201610",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83506,
				"displayName":"Adv Topics Com Networks",
				"subjectCode":"ECS",
				"courseNumber":"152C",
				"effectiveTermCode":"201410",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83507,
				"displayName":"Media Computation",
				"subjectCode":"ECS",
				"courseNumber":"012",
				"effectiveTermCode":"201503",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83508,
				"displayName":"Analysis of Algorithms",
				"subjectCode":"ECS",
				"courseNumber":"222A",
				"effectiveTermCode":"201603",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83509,
				"displayName":"Algorithm Design",
				"subjectCode":"ECS",
				"courseNumber":"122B",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83510,
				"displayName":"Computer Networks",
				"subjectCode":"ECS",
				"courseNumber":"152A",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				98
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83511,
				"displayName":"Computer Networks",
				"subjectCode":"ECS",
				"courseNumber":"152B",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				98
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83512,
				"displayName":"Software Engineering",
				"subjectCode":"ECS",
				"courseNumber":"260",
				"effectiveTermCode":"201610",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83515,
				"displayName":"Network Theory",
				"subjectCode":"ECS",
				"courseNumber":"253",
				"effectiveTermCode":"201803",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83516,
				"displayName":"Ethics in an Age of Tech",
				"subjectCode":"ECS",
				"courseNumber":"188",
				"effectiveTermCode":"201801",
				"sequencePattern":"004",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				100
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83517,
				"displayName":"Intro to Computers",
				"subjectCode":"ECS",
				"courseNumber":"015",
				"effectiveTermCode":"201110",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				98
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83518,
				"displayName":"Programming Languages",
				"subjectCode":"ECS",
				"courseNumber":"140B",
				"effectiveTermCode":"201610",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83520,
				"displayName":"Database Systems",
				"subjectCode":"ECS",
				"courseNumber":"165A",
				"effectiveTermCode":"201610",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":83522,
				"displayName":"Web Programming",
				"subjectCode":"ECS",
				"courseNumber":"162",
				"effectiveTermCode":"201710",
				"sequencePattern":"A",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				99
				],
				"note":null,
				"scheduleId":221
			},
			{  
				"id":84392,
				"displayName":"Hist Theor Ant Ling",
				"subjectCode":"ANT",
				"courseNumber":"205",
				"effectiveTermCode":"199001",
				"sequencePattern":"001",
				"unitsLow":4.0,
				"unitsHigh":null,
				"year":2018,
				"tagIds":[  
				],
				"note":null,
				"scheduleId":221
			}
			];

		}
	};
};

export default rolesTable;
